import { z } from "zod";

export const apiContractMetaSchema = z.object({
  method: z.enum(["GET", "POST", "PATCH", "PUT", "DELETE"]),
  path: z.string().startsWith("/api/"),
  audience: z.enum(["storefront", "seller", "admin"]),
  auth: z.enum(["none", "session"]),
  roles: z.array(z.enum(["CUSTOMER", "SELLER", "ADMIN", "SUPER_ADMIN"])),
});

export type ApiContract = z.infer<typeof apiContractMetaSchema> & {
  description: string;
};

export const API_CONTRACTS: ApiContract[] = [
  {
    method: "GET",
    path: "/api/health",
    audience: "storefront",
    auth: "none",
    roles: [],
    description: "Storefront health check",
  },
  {
    method: "GET",
    path: "/api/health",
    audience: "seller",
    auth: "none",
    roles: [],
    description: "Seller health check",
  },
  {
    method: "GET",
    path: "/api/health",
    audience: "admin",
    auth: "none",
    roles: [],
    description: "Admin health check",
  },
  {
    method: "POST",
    path: "/api/auth/login",
    audience: "storefront",
    auth: "none",
    roles: [],
    description: "Customer email/password login",
  },
  {
    method: "POST",
    path: "/api/auth/login",
    audience: "seller",
    auth: "none",
    roles: [],
    description: "Seller email/password login",
  },
  {
    method: "POST",
    path: "/api/auth/login",
    audience: "admin",
    auth: "none",
    roles: [],
    description: "Admin email/password login",
  },
  {
    method: "GET",
    path: "/api/auth/session",
    audience: "storefront",
    auth: "session",
    roles: ["CUSTOMER"],
    description: "Get the authenticated customer session",
  },
  {
    method: "POST",
    path: "/api/auth/register",
    audience: "storefront",
    auth: "none",
    roles: [],
    description: "Create a customer shopping account",
  },
  {
    method: "POST",
    path: "/api/auth/register",
    audience: "seller",
    auth: "none",
    roles: [],
    description: "Create a seller account pending business approval",
  },
  {
    method: "POST",
    path: "/api/v1/kyc",
    audience: "seller",
    auth: "session",
    roles: ["SELLER"],
    description: "Submit seller KYC documents",
  },
  {
    method: "POST",
    path: "/api/v1/media/documents",
    audience: "seller",
    auth: "session",
    roles: ["SELLER"],
    description: "Upload a private seller KYC document",
  },
  {
    method: "POST",
    path: "/api/v1/sellers/approval",
    audience: "admin",
    auth: "session",
    roles: ["ADMIN", "SUPER_ADMIN"],
    description: "Approve or reject seller onboarding after KYC review",
  },
  {
    method: "GET",
    path: "/api/v1/sellers/:sellerId",
    audience: "admin",
    auth: "session",
    roles: ["ADMIN", "SUPER_ADMIN"],
    description: "View seller registration, KYC status, and document metadata",
  },
  {
    method: "GET",
    path: "/api/v1/sellers/:sellerId/documents/:documentId",
    audience: "admin",
    auth: "session",
    roles: ["ADMIN", "SUPER_ADMIN"],
    description: "View a seller KYC document through an authorized private endpoint",
  },


  {
    method: "GET",
    path: "/api/auth/session",
    audience: "seller",
    auth: "session",
    roles: ["SELLER"],
    description: "Get the authenticated seller session",
  },
  {
    method: "GET",
    path: "/api/auth/session",
    audience: "admin",
    auth: "session",
    roles: ["ADMIN", "SUPER_ADMIN"],
    description: "Get the authenticated admin session",
  },
  {
    method: "POST",
    path: "/api/auth/logout",
    audience: "storefront",
    auth: "none",
    roles: [],
    description: "Revoke the current customer session and clear the session cookie",
  },
  {
    method: "POST",
    path: "/api/auth/logout",
    audience: "seller",
    auth: "none",
    roles: [],
    description: "Revoke the current seller session and clear the session cookie",
  },
  {
    method: "POST",
    path: "/api/auth/logout",
    audience: "admin",
    auth: "none",
    roles: [],
    description: "Revoke the current admin session and clear the session cookie",
  },
  {
    method: "GET",
    path: "/api/v1/catalog/categories",
    audience: "storefront",
    auth: "none",
    roles: [],
    description: "Public active marketplace categories",
  },
  {
    method: "GET",
    path: "/api/v1/catalog/products",
    audience: "storefront",
    auth: "none",
    roles: [],
    description: "Public catalog listing of live products only",
  },
  {
    method: "GET",
    path: "/api/v1/addresses",
    audience: "storefront",
    auth: "session",
    roles: ["CUSTOMER"],
    description: "List customer delivery addresses",
  },
  {
    method: "POST",
    path: "/api/v1/addresses",
    audience: "storefront",
    auth: "session",
    roles: ["CUSTOMER"],
    description: "Create a customer delivery address",
  },
  {
    method: "POST",
    path: "/api/v1/checkout",
    audience: "storefront",
    auth: "session",
    roles: ["CUSTOMER"],
    description: "Create an order from the authenticated customer cart",
  },
  {
    method: "GET",
    path: "/api/v1/orders",
    audience: "storefront",
    auth: "session",
    roles: ["CUSTOMER"],
    description: "List authenticated customer orders",
  },
  {
    method: "GET",
    path: "/api/v1/cart",
    audience: "storefront",
    auth: "session",
    roles: ["CUSTOMER"],
    description: "Customer cart",
  },
  {
    method: "POST",
    path: "/api/v1/cart",
    audience: "storefront",
    auth: "session",
    roles: ["CUSTOMER"],
    description: "Add a live product variant to the customer cart",
  },
  {
    method: "PUT",
    path: "/api/v1/cart",
    audience: "storefront",
    auth: "session",
    roles: ["CUSTOMER"],
    description: "Update cart item quantity",
  },
  {
    method: "DELETE",
    path: "/api/v1/cart",
    audience: "storefront",
    auth: "session",
    roles: ["CUSTOMER"],
    description: "Remove a product variant from the customer cart",
  },
  {
    method: "GET",
    path: "/api/v1/categories",
    audience: "seller",
    auth: "session",
    roles: ["SELLER"],
    description: "Seller category selector",
  },
  {
    method: "POST",
    path: "/api/v1/products",
    audience: "seller",
    auth: "session",
    roles: ["SELLER"],
    description: "Create product draft scoped to the authenticated seller",
  },
  {
    method: "POST",
    path: "/api/v1/qc-submissions",
    audience: "seller",
    auth: "session",
    roles: ["SELLER"],
    description: "Submit seller-owned product for QC",
  },
  {
    method: "GET",
    path: "/api/v1/sellers",
    audience: "admin",
    auth: "session",
    roles: ["ADMIN", "SUPER_ADMIN"],
    description: "List sellers for onboarding and approval",
  },
  {
    method: "POST",
    path: "/api/v1/qc",
    audience: "admin",
    auth: "session",
    roles: ["ADMIN", "SUPER_ADMIN"],
    description: "Approve or reject a QC submission",
  },
  {
    method: "GET",
    path: "/api/v1/themes",
    audience: "admin",
    auth: "session",
    roles: ["ADMIN", "SUPER_ADMIN"],
    description: "Theme drafts, published theme, and revision history",
  },
];

export function contractsForAudience(audience: ApiContract["audience"]): ApiContract[] {
  return API_CONTRACTS.filter((contract) => contract.audience === audience);
}
